import re
from math import sqrt

def modes(outcar,nat):

    """Read OUTCAR file generated by VASP Hessian run and extract eigenvalues
    and eigen vectors"""

    outcar_fh=open(outcar,'r')
    eigvals = [ 0.0 for i in range(nat*3) ]
    eigvecs = [ 0.0 for i in range(nat*3) ]
    norms   = [ 0.0 for i in range(nat*3) ]
    
    while True:
        line = outcar_fh.readline()
        if not line:
            break

        if "Eigenvectors after division by SQRT(mass)" in line:
            outcar_fh.readline() # empty line
            outcar_fh.readline() # Eigenvectors and eigenvalues of the dynamical matrix
            outcar_fh.readline() # ----------------------------------------------------
            outcar_fh.readline() # empty line

            for i in range(nat*3): # all frequencies should be supplied, regardless of those requested to calculate
                outcar_fh.readline() # empty line
                p = re.search(r'^\s*(\d+).+?([\.\d]+) cm-1', outcar_fh.readline())
                eigvals[i] = float(p.group(2))
                outcar_fh.readline() # X         Y         Z           dx          dy          dz
                eigvec = []
                for j in range(nat):
                    tmp = outcar_fh.readline().split()
                    eigvec.append([ float(tmp[x]) for x in range(3,6) ])
                eigvecs[i] = eigvec
                norms[i] = sqrt( sum( [abs(x)**2 for sublist in eigvec for x in sublist] ) )
            return eigvals, eigvecs, norms
            
    #print "[get_modes_from_OUTCAR]: ERROR Couldn't find 'Eigenvectors after division by SQRT(mass)' in OUTCAR. Use 'NWRITE=3' in INCAR. Exiting..."
